---
    - hosts: prod
      tasks:
        - name: Git pull and redeploy
          shell: |
            cd /home/raghav/DSC/Bootcamp-2022/bootcamp-feedback-server
            git pull
            docker-compose down
            docker-compose up --build -d